### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by hasenstein** [Focus/youtubequality#5]
Yesterday I watched one video and it worked - the video loaded in 720p initially but after a split second this extension kicked in and switched it to the desired 480p (I don't need more for most stuff).

But I just watched 3 videos like this one

https://www.youtube.com/watch?v=o0kvlFKt8ew&ab_channel=GreshamCollege

and nothing happened - the videos loaded in 720p. The extension was active (symbol is visible) and set to "480".

**Comment by Focus** [comment]
I can't seem to be able to replicate this. Does it still persist? The video linked is working fine for me.

**Comment by hasenstein** [comment]
I just reinstalled the extension (I I had removed it), clicked the above youtube link, and the video was in 480 (when it normally would be 720p with my screen settings). The only strange thing: the Youtube settings icon shows red "HD" as it only does for 720p and above, but when I click on it I see that 480p is selected. So this seems to confuse the Youtube player.

**Comment by Focus** [comment]
The youtube player sometimes takes a while to adjust the setting but I don't think I have witnessed what you are describing.

**Comment by hasenstein** [comment]
As you can see it's not a timing issue, it stays like that.

![unbenannt-1](https://cloud.githubusercontent.com/assets/199179/7274667/052a15c4-e8ff-11e4-9a11-8827e71f7c21.png)

**Comment by hasenstein** [comment]
When I reload the page it works, after less than a second the "HD" is gone. Next I tried another video and the problem persists, reloading many times or not. Seems like one of those really nasty seemingly inconsistent problems.

**Comment by Focus** [comment]
Sorry but I cannot reproduce the problem at all. I tried to even use the new youtube player that you are using in the screen cap. The only thing I can think of is that something else might be setting the quality back. There is not much I can do I'm afraid.
